### ISSUE TITLE
Backtracking Bug

### ISSUE THREAD

**Issue by modderme123** [bbchallenge/bbchallenge-deciders#1]
I believe this https://bbchallenge.org/55897188&s=10000&w=300&ox=0.5 should be decidable using backtracking, because values get written to the tape between each transition. 

However, it seems that the value that would be written to the tape is currently ignored (https://github.com/bbchallenge/bbchallenge-deciders/blob/main/decider-backward-reasoning/main.go#L66) which could create both false positives and false negatives.

**Comment by tcosmo** [comment]
You are right!

When I wrote the decider I sort of convinced myself that you could ignore write information since it is immediately overwritten by the read information. For instance with this example: https://bbchallenge.org/4843748

However you example proves me wrong.

Would you be interested in debugging this decider :D?

Consequently:

1. I have cancelled the results of https://discuss.bbchallenge.org/t/decider-backward-reasoning/35 meaning that all the machines it decided are now back to being **undecided**.

2. To better keep track of these events I have put the index of undecided machines on github: https://github.com/bbchallenge/bbchallenge-undecided-index. At the moment it contains only the results of https://discuss.bbchallenge.org/t/decider-cyclers/33 and https://discuss.bbchallenge.org/t/decider-translated-cyclers/34.

3. I also talked about in https://discuss.bbchallenge.org/t/april-1st-2022-bug-in-backward-reasoning-new-git-repo-for-undecided-index/39

Thank you very much for raising the issue!

**Comment by EricESeverson** [comment]
We have a couple students who have been talking about this, and who stumbled upon this issue.
So hopefully next week the partial progress they have on getting a working backwards reasoning decider results in something that can be applied to the seed database.

**Comment by tcosmo** [comment]
That's really cool! Don't hesitate to give me their names/pseudo so they can be credited for their work on https://discuss.bbchallenge.org/t/decider-backward-reasoning/35/2

Of course, they are welcome to talk about the issue on the forum!

Thank you for raising this issue and working on solving it!

**Comment by modderme123** [comment]
Pinging @atticuscull who originally discovered this. I believe @pg132 and @DunDunDunDone also worked on the problem

**Comment by DunDunDunDone** [comment]
That is correct. I might take a look at some of the code soon, but if there are other particular or specific tasks that need to be done, please notify me!

**Comment by tcosmo** [comment]
Even if not jumping in the code, if you want for instance to provide some pseudo-code of what is a correct backward reasoning, accompanied by an argument of why the pseudo-code is correct, that'd be really helpful!

You could post it there for instance: https://discuss.bbchallenge.org/t/decider-backward-reasoning/35/2

**Comment by tcosmo** [comment]
Solved with #5 

Great work!!
